databases:
  - name: openxeco-db
    databaseName: openxeco
    plan: free

services:
  - type: web
    name: openxeco-api
    runtime: docker
    plan: free
    dockerfilePath: .docker/Dockerfile.render-api
    envVars:
      - key: ENVIRONMENT
        value: prod
      - key: DEBUG
        value: "false"
      - key: DB_DRIVER
        value: postgresql+psycopg2
      - key: DB_HOSTNAME
        fromDatabase:
          name: openxeco-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: openxeco-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: openxeco-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: openxeco-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: openxeco-db
          property: password
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: SECURITY_SALT
        generateValue: true
      - key: IMAGE_FOLDER
        value: /app/media
      - key: DOCUMENT_FOLDER
        value: /app/documents
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "true"
      - key: MAIL_USE_SSL
        value: "false"
      - key: MAIL_USERNAME
        value: "noreply@openxeco.local"
      - key: MAIL_PASSWORD
        value: "password123"
      - key: MAIL_DEFAULT_SENDER
        value: "noreply@openxeco.local"
      - key: INITIAL_ADMIN_EMAIL
        value: "admin@openxeco.local"
      - key: INITIAL_ADMIN_PASSWORD
        value: "Admin123!"
      - key: CORS_DOMAINS
        value: "onrender.com,localhost"
  - type: web
    name: openxeco-web
    runtime: docker
    plan: free
    dockerfilePath: oxe-web-community/Dockerfile.web
    envVars:
      - key: NODE_ENV
        value: production
