services:

  # API Service
  - type: web
    name: openxeco-api-docker
    runtime: docker
    plan: free
    dockerfilePath: .docker/Dockerfile.render-api
    env: production
    envVars:
      - key: ENVIRONMENT
        value: prod
        sync: false  # Set manually in Render dashboard
      - key: MAIL_DEFAULT_SENDER
        sync: false  # Set manually in Render dashboard
      - key: IMAGE_FOLDER
        value: /app/media
      - key: DOCUMENT_FOLDER
        value: /app/documents
      - key: INITIAL_ADMIN_EMAIL
        sync: false  # Set manually in Render dashboard
      - key: INITIAL_ADMIN_PASSWORD
        sync: false  # Set manually in Render dashboard

  # Community Web App  
  - type: web
    name: openxeco-community
    envVars:
      - key: PORT
        value: 10000
      - key: REACT_APP_API_URL
        value: https://openxeco-api-docker.onrender.com
